version: '3.8'

services:
  db:
    image: alpine
    container_name: ping_db
    command: >
      sh -c "apk add --no-cache sqlite && mkdir -p /db && touch /db/ping_stats.db &&
      sqlite3 /db/ping_stats.db 'CREATE TABLE IF NOT EXISTS ping_data (
        id INTEGER PRIMARY KEY AUTOINCREMENT, 
        server TEXT, 
        timestamp REAL, 
        response_time REAL
      );' && tail -f /dev/null"
    volumes:
      - ping_data:/db  # ✅ Now uses `/db` to match `monitor_api`
    restart: always

  monitor_api:
    build: ./api
    container_name: monitor_api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_PATH=/db/ping_stats.db  # ✅ Matches the `db` container path
    volumes:
      - ping_data:/db  # ✅ Uses the exact same volume and path as `db`
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ping_monitor:/ping_monitor
    restart: always

volumes:
  ping_data:  # ✅ Shared volume for `/db/ping_stats.db`
