version: '3.8'

services:
  db:
    image: alpine
    container_name: ping_db
    command: >
      sh -c "apk add --no-cache sqlite && mkdir -p /data && touch /data/ping_stats.db &&
      sqlite3 /data/ping_stats.db 'CREATE TABLE IF NOT EXISTS ping_data (
        id INTEGER PRIMARY KEY AUTOINCREMENT, 
        server TEXT, 
        timestamp REAL, 
        response_time REAL
      );' && tail -f /dev/null"
    volumes:
      - ping_data:/data  # ✅ Ensure database volume is mounted consistently
    restart: always

  monitor_api:
    build: ./api
    container_name: monitor_api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_PATH=/data/ping_stats.db  # ✅ Use the correct path
    volumes:
      - ping_data:/data  # ✅ Now matches db service!
      - /var/run/docker.sock:/var/run/docker.sock  # ✅ API must control other containers
      - ./ping_monitor:/ping_monitor  # ✅ Mounts ping_monitor directory
    restart: always

volumes:
  ping_data:  # ✅ Shared database volume
