version: '3.8'

services:
  db:
    image: alpine
    container_name: ping_db
    command: >
      sh -c "apk add --no-cache sqlite && mkdir -p /data && touch /data/ping_stats.db &&
      sqlite3 /data/ping_stats.db 'CREATE TABLE IF NOT EXISTS ping_data (
        id INTEGER PRIMARY KEY AUTOINCREMENT, 
        server TEXT, 
        timestamp REAL, 
        response_time REAL
      );' && tail -f /dev/null"
    volumes:
      - ping_data:/data  # ✅ Shared database volume
    restart: always

  monitor_api:
    build: ./api
    container_name: monitor_api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_PATH=/db/ping_stats.db
    volumes:
      - ping_data:/db  # ✅ Mount database separately
      - /var/run/docker.sock:/var/run/docker.sock  # Allow API to manage containers
      - ./ping_monitor:/ping_monitor  # ✅ Mount ping_monitor into monitor_api
    restart: always

  ping_monitor:
    build: ./ping_monitor
    container_name: ping_monitor
    depends_on:
      - db
    environment:
      - DB_PATH=/db/ping_stats.db
    volumes:
      - ping_data:/db  # ✅ Separate mount for database
      - ping_monitor:/app  # ✅ Separate mount for monitoring scripts
    command: ["python", "/app/driver.py"]
    restart: always

volumes:
  ping_data:  # ✅ Persistent database volume
  ping_monitor:  # ✅ Persistent volume for monitoring scripts
